name: Push event

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install build-essential
        run: sudo apt-get install build-essential gcc  -y
      - name: Install pipenv
        run: pip3 install -U pipenv
      - name: Install Deps
        run: pipenv install --dev --system
      - name: Launch test
        run: pytest --cov=./ --cov-report=xml --disable-pytest-warnings
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
